name: TrendWatchDesk Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "10 7 * * 1,3,5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Sanity: prove the workflow runs
      - name: Hello
        run: echo "Workflow is alive on $(date -u)!"

      # Ensure Python + deps
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install baseline deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance pillow pandas numpy requests pytz urllib3

      # Make sure output exists
      - name: Ensure output folder
        run: |
          mkdir -p output
          ls -la output || true

      # Run your bot with full logging
      - name: Run bot (tee log)
        run: |
          set -x
          python -u main.py 2>&1 | tee run.log
        env:
          PYTHONUNBUFFERED: "1"

      # Show logs in console
      - name: Print run.log
        if: always()
        run: |
          echo "===== BEGIN run.log ====="
          (test -f run.log && tail -n 300 run.log) || echo "run.log missing"
          echo "===== END run.log ====="

      # List output
      - name: Debug output folder
        if: always()
        run: |
          echo "== output listing =="
          ls -la output || true
          echo "== any pngs =="
          find output -maxdepth 1 -type f -name "*.png" -printf "%f\n" 2>/dev/null || true

      # Upload artifacts (optional)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_id }}
          path: |
            run.log
            output/**
