name: TrendWatchDesk Daily

on:
  schedule:
    - cron: "30 7 * * 1-5"   # 07:30 UTC (≈ 08:30 London weekdays)
  workflow_dispatch:

  permissions:
  contents: write 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run generator
        env:
          TZ: Europe/London
          PAGES_BASE: https://yoitskraft.github.io/trendwatchdesk-bot
        run: python main.py

          - name: List files
        run: |
          pwd
          ls -la
          echo "---- docs ----"
          ls -la docs || true

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-output
          path: docs

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.png docs/feed.xml
          git commit -m "Daily update" || echo "No changes"
          git push
