name: TrendWatchDesk Generate (Charts)

on:
  schedule:
    - cron: "10 7 * * 1,3,5"   # Mon/Wed/Fri 07:10 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance pillow pandas numpy requests

      - name: Ensure output folders
        run: |
          mkdir -p output/charts
          mkdir -p output/posters

      - name: Run daily charts
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -x
          python -u main.py 2>&1 | tee output/run.log

      - name: Print run.log
        if: always()
        run: |
          echo "===== BEGIN run.log ====="
          (test -f output/run.log && cat output/run.log) || echo "run.log missing"
          echo "===== END run.log ====="

      - name: Require PNGs
        run: |
          set -e
          COUNT=$(find output/charts -type f -name "*.png" | wc -l | tr -d ' ')
          echo "Charts PNG count: $COUNT"
          if [ "$COUNT" = "0" ]; then
            echo "::error::No charts generated."
            exit 1
          fi

      - name: Publish to 'charts' branch
        if: success()
        run: |
          rm -rf publish && mkdir publish
          cp -r output/* publish/

          cd publish
          git init
          git checkout -b charts
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git add -A
          git commit -m "Publish charts $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push -f origin charts

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: charts-run-${{ github.run_id }}
          path: output/**
