name: TrendWatchDesk Generate (Charts)

on:
  schedule:
    - cron: "10 7 * * 1,3,5"   # Mon/Wed/Fri 07:10 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance pillow pandas numpy requests pytz urllib3

      - name: Ensure output
        run: |
          mkdir -p output

      - name: Run charts mode
        env:
          PYTHONUNBUFFERED: "1"
          TWD_MODE: "charts"
        run: |
          set -x
          python -u main.py 2>&1 | tee run.log

      - name: Print run.log
        if: always()
        run: |
          echo "===== BEGIN run.log ====="
          (test -f run.log && tail -n 400 run.log) || echo "run.log missing"
          echo "===== END run.log ====="

      - name: Require charts
        if: always()
        run: |
          set -e
          COUNT=$(find output -maxdepth 1 -type f -name "*.png" 2>/dev/null | wc -l | tr -d ' ')
          echo "PNG count: $COUNT"
          if [ "$COUNT" = "0" ]; then
            echo "::error::No charts generated. Check run.log above for errors."
            exit 1
          fi

      - name: Publish charts to 'charts' branch
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          rm -rf publish && mkdir publish
          cp -r output/*.png publish/ 2>/dev/null || true
          cp -r output/caption_*.txt publish/ 2>/dev/null || true

          cd publish
          git init
          git checkout -b charts
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"

          git add -A
          git commit -m "Publish charts $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push -f origin charts

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: charts-${{ github.run_id }}
          path: |
            run.log
            output/**
