name: TrendWatchDesk • Daily Charts

on:
  schedule:
    - cron: "10 7 * * 1,3,5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (stable pins)
        run: |
          python -m pip install --upgrade pip
          pip install \
            yfinance==0.2.40 \
            pandas==2.2.2 \
            numpy==1.26.4 \
            pillow==10.4.0 \
            requests==2.32.3

      - name: Ensure folders
        run: |
          mkdir -p output/charts
          mkdir -p output/posters
          mkdir -p assets/logos
          mkdir -p assets/fonts

      - name: Run daily charts (attempt 1)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -x
          python -u main.py 2>&1 | tee output/run.log

      - name: Retry once if zero PNGs
        run: |
          set -e
          COUNT=$(find output/charts -type f -name "*.png" | wc -l | tr -d ' ')
          echo "PNG count after attempt 1: $COUNT"
          if [ "$COUNT" = "0" ]; then
            echo "Retrying once..."
            sleep 8
            python -u main.py 2>&1 | tee -a output/run.log
          fi

      - name: Show logs & tree
        if: always()
        run: |
          echo "===== BEGIN output/run.log ====="
          (test -f output/run.log && cat output/run.log) || echo "run.log missing"
          echo "===== END output/run.log ====="
          echo
          echo "===== OUTPUT TREE ====="
          (command -v tree >/dev/null && tree -a output || find output -maxdepth 3 -printf "%y %p\n") || true
          echo "======================="

      - name: Require charts (stop if zero)
        run: |
          set -e
          COUNT=$(find output/charts -type f -name "*.png" | wc -l | tr -d ' ')
          echo "Final charts PNG count: $COUNT"
          if [ "$COUNT" = "0" ]; then
            echo "::error::No charts generated."
            exit 1
          fi

      - name: Upload artifact (for debugging / Pages)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-output-${{ github.run_id }}
          path: output/**
