name: TrendWatchDesk Generate (Charts + Posters)

on:
  schedule:
    - cron: "10 7 * * 1,3,5"   # Mon/Wed/Fri 07:10 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python & pip
        run: |
          python --version
          pip --version

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance pillow pandas numpy requests pytz urllib3

      - name: Ensure output folder
        run: |
          mkdir -p output
          echo "Output dir:" && pwd && ls -la output || true

      # ---- Run daily charts ----
      - name: Run daily charts (CI mode)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -x
          python main.py --ci 2>&1 | tee run.log

      # ---- Run posters ----
      - name: Run news posters (CI mode)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -x
          python main.py --ci-posters 2>&1 | tee -a run.log

      - name: Print run.log to console
        if: always()
        run: |
          echo "===== BEGIN run.log ====="
          (test -f run.log && cat run.log) || echo "run.log missing"
          echo "===== END run.log ====="

      - name: Debug output folder
        if: always()
        run: |
          echo "== output listing =="
          ls -la output || true
          echo "== charts =="
          find output/charts -type f -name "*.png" || true
          echo "== posters =="
          find output/posters -type f -name "*.png" || true
          echo "== captions =="
          ls -la output/*caption* 2>/dev/null || true

      # ---- Publish both charts + posters ----
      - name: Publish to 'charts' branch (single-commit)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          rm -rf publish && mkdir publish
          cp -r output/* publish/ || true

          cd publish
          git init
          git checkout -b charts
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"

          git add -A
          git commit -m "Publish outputs $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push -f origin charts

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twd-run-${{ github.run_id }}
          path: |
            run.log
            output/**
