name: TrendWatchDesk Daily

on:
  schedule:
    - cron: "0 9 * * 1-5"  # every weekday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pillow yfinance requests urllib3 pytz

      - name: Run generator
        run: |
          echo "Running main.py..."
          python main.py
          echo "---- output ----"
          ls -la output || true

      - name: Upload images as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twd-output
          path: output/*.png
          if-no-files-found: warn

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.png || true
          git commit -m "Daily images $(date +'%Y%m%d')" || echo "No new images to commit"
          git push
