name: TrendWatchDesk Daily

on:
  workflow_dispatch:      # allows manual run
  schedule:
    - cron: "30 7 * * *"  # runs every day at 07:30 London time

permissions:
  contents: write         # needed so the workflow can commit the new images/docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate image + RSS
        run: |
          python main.py
          ls -la output

      - name: Commit output and docs
        run: |
          datestr=$(date +'%Y%m%d')
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add output docs
          git commit -m "Daily image ${datestr}" || echo "Nothing to commit"
          git push
