name: Docs Guard

on:
  pull_request:
    branches:
      - main

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run update_docs.py
        run: python update_docs.py

      - name: Verify docs are up to date
        run: |
          if ! git diff --exit-code OPERATIONS_GUIDE.md README.md; then
            echo "::error::Docs are out of sync. Please re-run update_docs.py and commit changes."
            exit 1
          fi
