name: Docs Autostamp

on:
  push:
    branches:
      - main

jobs:
  autostamp:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run update_docs.py
        run: python update_docs.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add OPERATIONS_GUIDE.md README.md
          git diff --cached --quiet && echo "No changes" || git commit -m "docs: autostamp update"
          git push
