name: Docs Autostamp
on:
  push:
    branches: [ main ]
    paths:
      - "main.py"
      - "controls.py"
      - "assets/logos/**"
      - "README.md"
      - "OPERATIONS_GUIDE.md"
      - "scripts/update_docs.py"
  schedule:
    - cron: "0 8 * * *"   # daily 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  autostamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update docs
        run: python scripts/update_docs.py
      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md OPERATIONS_GUIDE.md
            git commit -m "docs: autostamp README/Operations Guide"
            git push
          else
            echo "No doc changes."
          fi
