name: TWD Posters (3-hourly)

on:
  schedule:
    - cron: "0 */3 * * *"      # every 3 hours UTC
  workflow_dispatch:

jobs:
  posters:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance pillow pandas numpy requests pytz urllib3

      - name: Ensure output dirs
        run: |
          mkdir -p output/posters

      - name: Run posters mode
        env:
          PYTHONUNBUFFERED: "1"
          TWD_MODE: "posters"
        run: |
          set -x
          python -u main.py 2>&1 | tee run.log

      - name: Print log
        if: always()
        run: |
          echo "===== BEGIN run.log ====="
          (test -f run.log && tail -n 400 run.log) || echo "run.log missing"
          echo "===== END run.log ====="

      - name: Publish posters to 'posters' branch
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          rm -rf publish_posters && mkdir -p publish_posters

          # copy poster PNGs if any; add placeholder otherwise to keep branch alive
          cp -r output/posters/*.png publish_posters/ 2>/dev/null || true
          if [ -z "$(ls -A publish_posters 2>/dev/null)" ]; then
            echo "No posters this run, adding placeholder."
            echo "keep" > publish_posters/.keep
          fi

          cd publish_posters
          git init
          git checkout -b posters
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"

          git add -A
          git commit -m "Posters $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push -f origin posters

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: posters-${{ github.run_id }}
          path: |
            run.log
            output/**
